name: 提交错误
description: 各种各样的奇怪的问题都可以提交。
body:
    - type: markdown
      attributes:
          value: |
              在开始提交 BUG 前，请先前往 [里程碑](https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/milestones) 检查已经在计划中的事项，如果没有再回来提交以防重复。
    - type: dropdown
      attributes:
          label: 错误来源
          options:
              - QQ Bot
              - Stapxs QQ Lite（All）
              - Stapxs QQ Lite（Web）
              - Stapxs QQ Lite（Electron）
              - 其他
    - type: textarea
      attributes:
          label: 描述错误
          description: 发生了什么呢 …… 简单说一下就好了（x
    - type: textarea
      attributes:
          label: 复现流程
          description: 如果你可以重现这个 BUG，你可以在下面留下操作流程
    - type: textarea
      attributes:
          label: 截图
          description: 如果有附加的截图，可以添加在下面
    - type: textarea
      attributes:
          label: 版本信息
          description: 执行 “设置 - 高级 - 输出调试信息” 获取应用运行的版本信息，粘贴到这儿以方便快速了解运行环境
    - type: textarea
      attributes:
          label: 更多
          description: 还有别的要说吗？比如说控制台的报错之类的，都可以塞这儿
